SELECT * FROM TAB; -- TABLE 확인
SELECT * FROM CHILD_T;
DROP TABLE PARENT_T; --TABLE 제거
DROP TABLE CHILD_T;
------------------------------------------------------------
CREATE TABLE PARENT_T (
        P_ID VARCHAR2(4) NOT NULL
        );
-- ALTER TABLE 넣어질테이블명 ADD CONSTRAINT 키명 PRIMARY KEY(속성);

ALTER TABLE PARENT_T ADD CONSTRAINT P_PK PRIMARY KEY(P_ID); -- 프라이머리키 생성

CREATE TABLE CHILD_T (  --자식 테이블
    C_ID VARCHAR2(4) NOT NULL,
    P_ID VARCHAR2(4)
    );
ALTER TABLE CHILD_T ADD CONSTRAINT C_PK PRIMARY KEY(C_ID); 
ALTER TABLE CHILD_T ADD CONSTRAINT C_FK FOREIGN KEY (P_ID) REFERENCES PARENT_T(P_ID);

INSERT INTO PARENT_T VALUES('A');
INSERT INTO PARENT_T VALUES('B');
COMMIT;
SELECT P_ID FROM PARENT_T;

INSERT INTO CHILD_T VALUES('a','A');
UPDATE CHILD_T SET p_id = 'B' WHERE p_id = 'A';
UPDATE CHILD_T SET p_id = 'A' WHERE p_id = 'B';
COMMIT;
SELECT * FROM CHILD_T;

CREATE TABLE PARENT2(
P_ID VARCHAR2(10) PRIMARY KEY, P_NAME VARCHAR2(4)
CONSTRAINT P_FK REFERENCES PARENT_T(P_ID)
);
SELECT * FROM PARENT2;