--테이블 셋팅
CREATE TABLE SINGER(
            SINGER_ID NUMBER,
            SINGER_NAME VARCHAR2(20),
            MUSIC_ID NUMBER
            );
ALTER TABLE SINGER ADD CONSTRAINT SINGER_FK FOREIGN KEY (MUSIC_ID) 
REFERENCES MUSIC(MUSIC_ID);

CREATE TABLE MUSIC(
            MUSIC_ID NUMBER,
            GENRE VARCHAR2(20)
            );


--1
SELECT AVG(NVL(COMM,0)) FROM EMP;


--2 
SELECT ENAME, TRUNC(SYSDATE)- TRUNC(HIREDATE)
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP);


--3
ALTER TABLE MUSIC ADD CONSTRAINT MUSICC_PK PRIMARY KEY(MUSIC_ID);
CREATE TABLE MUSIC2(
            MUSIC_ID NUMBER,
            GENRE VARCHAR2(20)
            );
ALTER TABLE MUSIC2 ADD CONSTRAINT MUSIC_FK FOREIGN KEY (MUSIC_ID) 
REFERENCES MUSIC(MUSIC_ID);


--4
ALTER TABLE SINGER DROP CONSTRAINT SINGER_FK;

--5
SELECT A.EMPNO, A.ENAME
FROM EMP A
WHERE A.SAL = (SELECT MAX(B.SAL) FROM EMP B);

--6
SELECT A.ENAME
FROM EMP A
WHERE A.SAL > (SELECT B.SAL FROM EMP B WHERE ENAME = 'JONES');

--7
--JOB를 그룹화하지 않았기 때문이다.
SELECT JOB, MAX(SAL)
FROM EMP
WHERE JOB = 'SALESMAN';
--수정 후
SELECT JOB, MAX(SAL)
FROM EMP
WHERE JOB = 'SALESMAN' 
group by JOB;

--8
SELECT D.DEPTNO, COUNT(E.DEPTNO), AVG(NVL(E.SAL,0)), D.LOC
FROM EMP E, DEPT D group by D.DEPTNO, D.LOC;

SELECT AVG(NVL(SAL,0)) FROM EMP WHERE JOB = 'SALESMAN';