SELECT * FROM EMPLOYEES, DEPARTMENTS;
------------------------------
--JOIN 동등 조인(내부 조인)
SELECT * 
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
ORDER BY A.EMPLOYEE_ID ASC;
SELECT * 
FROM EMPLOYEES A, DEPARTMENTS B
WHERE A.MANAGER_ID = B.MANAGER_ID
ORDER BY A.EMPLOYEE_ID ASC;
------------------------------
SELECT A.EMPLOYEE_ID, A.DEPARTMENT_ID, B.DEPARTMENT_NAME, C.LOCATION_ID, C.CITY
FROM EMPLOYEES A, DEPARTMENTS B, LOCATIONS C
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
AND B.LOCATION_ID = C.LOCATION_ID;
------------------------------
SELECT COUNT(*) 조인된건수
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;
------------------------------
--아우터 조인
SELECT E.EMPLOYEE_ID 사원번호, E.FIRST_NAME||' '||E.LAST_NAME 이룸,
        D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+) --위부조인, 부족한 행 데이터 쪽에 기술한다.
ORDER BY E.EMPLOYEE_ID;                     --레프트 아우터 조인
------------------------------
--자체 조인 (SELF JOIN)
--테이블이 1개인 조인
SELECT E.EMPLOYEE_ID, E.FIRST_NAME|| ' ' || E.LAST_NAME, E.MANAGER_ID,
        EE.FIRST_NAME|| ' ' || EE.LAST_NAME MANAGER_NAME
FROM EMPLOYEES E, EMPLOYEES EE
WHERE E.MANAGER_ID = EE.EMPLOYEE_ID
ORDER BY E.EMPLOYEE_ID;
------------------------------
SELECT DEPARTMENT_ID FROM EMPLOYEES
UNION
SELECT DEPARTMENT_ID FROM DEPARTMENTS;
------------------------------
SELECT DEPARTMENT_ID FROM EMPLOYEES
UNION ALL
SELECT DEPARTMENT_ID FROM DEPARTMENTS;
------------------------------
--교집합
SELECT DEPARTMENT_ID FROM EMPLOYEES
INTERSECT
SELECT DEPARTMENT_ID FROM DEPARTMENTS;
------------------------------
SELECT DEPARTMENT_ID FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID FROM EMPLOYEES;
------------------------------
SELECT * --6                메인쿼리
FROM EMPLOYEES E --5
WHERE E.SALARY = ( --4      서브쿼리
                    SELECT SALARY --3
                    FROM EMPLOYEES --1
                    WHERE LAST_NAME = 'De Haan' --2
                    );
--------------------
--다중 행 서브쿼리
SELECT *
FROM EMPLOYEES E
WHERE E.SALARY IN (
                    SELECT MIN(SALARY) 최저급여
                    FROM EMPLOYEES
                    GROUP BY DEPARTMENT_ID
                    )
ORDER BY E.SALARY DESC;